- hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Create XDG directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ lookup('env', 'DOAS_USER') }}"
        group: "{{ lookup('env', 'DOAS_USER') }}"
        mode: '0755'
      loop:
        - /home/{{ lookup('env', 'DOAS_USER') }}/.config/X11
        - /home/{{ lookup('env', 'DOAS_USER') }}/.config/cwm

    - name: Install X session file
      ansible.builtin.file:
        src: "{{ playbook_dir }}/config/xsession"
        dest: "/home/{{ lookup('env', 'DOAS_USER') }}/.xsession"
        state: link
        force: true
        follow: false

    - name: Install X11 configuration files
      ansible.builtin.file:
        src: "{{ playbook_dir }}/config/{{ item.src }}"
        dest: "/home/{{ lookup('env', 'DOAS_USER') }}/{{ item.dest }}"
        state: link
        force: true
        follow: false
      loop:
        - { src: "X11/Xresources", dest: ".config/X11/Xresources" }
        - { src: "cwm/cwmrc", dest: ".config/cwm/cwmrc" }
