- hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: Create XDG Base Directory structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ lookup('env', 'DOAS_USER') }}"
        group: "{{ lookup('env', 'DOAS_USER') }}"
        mode: '0755'
        recurse: true
      loop:
        - /home/{{ lookup('env', 'DOAS_USER') }}/.config
        - /home/{{ lookup('env', 'DOAS_USER') }}/.local
        - /home/{{ lookup('env', 'DOAS_USER') }}/.local/share
        - /home/{{ lookup('env', 'DOAS_USER') }}/.local/share/gnupg
        - /home/{{ lookup('env', 'DOAS_USER') }}/.local/bin
        - /home/{{ lookup('env', 'DOAS_USER') }}/.local/share/applications
        - /home/{{ lookup('env', 'DOAS_USER') }}/.local/share/icons
        - /home/{{ lookup('env', 'DOAS_USER') }}/.local/share/fonts
        - /home/{{ lookup('env', 'DOAS_USER') }}/.local/share/themes
        - /home/{{ lookup('env', 'DOAS_USER') }}/.local/share/desktop-directories

    - name: Copy bin folder to XDG local bin directory
      synchronize:
        src: '{{ playbook_dir }}/bin/'
        dest: "/home/{{ lookup('env', 'DOAS_USER') }}/.local/bin/"
        delete: true
        recursive: true