# Set your locale(1)
export LANG=en_US.UTF-8

# Set your environment (korn shell)
export ENV=$HOME/.config/ksh/kshrc

# No core dumps!
ulimit -Sc 0

# Merge our X resources
xrdb -merge $HOME/.config/X11/Xresources

# Set background colour
setroot -solid dimgrey

# Make sure that bell is off!
xset b off

# Fix scaling of some X/QT programs
xrandr --dpi 96

# Automatically lock X
xidle -delay 5 -sw -timeout 300 -program "/usr/X11R6/bin/xlock -mode qix" &

# Launch status bar in small terminal windows
# Positioned for 1400x900 display - bottom left
xterm -geometry 200x20+0+880 -e "$HOME/.local/bin/date-bar" &
xterm -geometry 100x20+200+880 -e "$HOME/.local/bin/desktop-id" &

# Run our window manager with XDG-compliant config.
# Can later be replaced with `exec startxfce4` if desired.
# exec runs it in the foreground - X will exit when the cwm proc exits.
exec cwm -c $HOME/.config/cwm/cwmrc
