# Set your locale(1)
export LANG=en_US.UTF-8

# Set your environment (korn shell)
export ENV=$HOME/.config/ksh/kshrc

# Enable scrolling with trackpoint and middle button
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1

xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2

xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5

# No core dumps!
ulimit -Sc 0

# Merge our X resources
xrdb -merge $HOME/.config/X11/Xresources

# Set background colour
xsetroot -solid dimgrey

# Make sure that bell is off!
xset b off

# Fix scaling of some X/QT programs
xrandr --dpi 96

# Automatically lock X
xidle -delay 5 -sw -timeout 300 -program "/usr/X11R6/bin/xlock -mode qix" &

# Launch status bar in small terminal windows
xterm -name desktop-id -class desktop-id -e "$HOME/.local/bin/desktop-id" &
xterm -name date-bar -class date-bar -e "$HOME/.local/bin/date-bar" &

# Run our window manager with XDG-compliant config.
# Can later be replaced with `exec startxfce4` if desired.
# exec runs it in the foreground - X will exit when the cwm proc exits.
exec cwm -c $HOME/.config/cwm/cwmrc
